projects:
  app:
    schemaPath: src/schema/typeDefs.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  prisma:
    schemaPath: src/prisma-generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml
